decision_variables:
    name_experiment: tune_parameters
    tune_parameters: True
    apply_optimization: False
    show_figures: True
    save_figures: False

experiment_parameters:
    number_of_runs: 5
    enemy: 2
    generations: 3


tuning_parameters:
# choose a number of  tuning parameters and define the type of the parameter (integer, float, string).
    tuning_parameter_1:
        name: max_stagnation
        type: integer
        l_bound: 2
        u_bound: 4
        num_variations: 3
    tuning_parameter_2:
        name: weight_mutate_rate
        type: float
        l_bound: 0.7
        u_bound: 0.9
        num_variations: 3
    tuning_parameter_3:
        name: bias_mutate_rate
        type: float
        l_bound: 0.7
        u_bound: 0.9
        num_variations: 3

