decision_variables:
    name_experiment: final_results
    tune_parameters: False
    apply_optimization: True
    show_figures: False
    save_figures: False
    final_results: True

experiment_parameters:
    number_of_runs: 10
    enemies: [1,5,8]
    generations: 30


tuning_parameters:
# choose a number of  tuning parameters and define the type of the parameter (integer, float, string).
    tuning_parameter_1:
        name: max_stagnation
        type: integer
        l_bound: 2
        u_bound: 4
        num_variations: 3
    tuning_parameter_2:
        name: weight_mutate_rate
        type: float
        l_bound: 0.7
        u_bound: 0.9
        num_variations: 3
    tuning_parameter_3:
        name: bias_mutate_rate
        type: float
        l_bound: 0.7
        u_bound: 0.9
        num_variations: 3

